CREATE TABLE DICTIONARY_VERSION (
  VALUE VARCHAR2(20) NOT NULL
);

CREATE TABLE LEMMA (
  TEXT VARCHAR2(100) NOT NULL ,
  JSON VARCHAR2(4000) NOT NULL ,
  ID INT NOT NULL,
  REVISION INT NULL,
  STATE TINYINT NOT NULL,
  PRIMARY KEY (ID),
);
