CREATE TABLE DICTIONARY_VERSION (
  TYPE VARCHAR(10) NOT NULL,
  VALUE VARCHAR(20) NOT NULL
);

CREATE TABLE LEMMA (
  TEXT     VARCHAR(100)  NOT NULL,
  JSON     VARCHAR(4000) NOT NULL,
  ID       INT           NOT NULL,
  REVISION INT           NOT NULL,
  STATE    TINYINT       NOT NULL,
  PRIMARY KEY (ID)
);

-- do not intersect with opercorpora id which is positive
CREATE TABLE LEMMA_ID (
  VALUE INT AUTO_INCREMENT PRIMARY KEY
);
INSERT INTO LEMMA_ID (VALUE) VALUES (0);

CREATE TABLE REVISION (
  VALUE INT AUTO_INCREMENT PRIMARY KEY
);
INSERT INTO REVISION (VALUE) VALUES (0);

CREATE TABLE DICTIONARY_LINK (
  DESCRIPTION VARCHAR(100) NOT NULL,
  REVISION    INT,
  PRIMARY KEY (DESCRIPTION)
);
